In [ ]:
!wget "https://storage.googleapis.com/kaggle-data-sets/306/666/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260307%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260307T054502Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=187c940c75e240ebfc9d161e8437a76f0b488efb40acb7d0fafb80ac1ed2690c8c95776259a94f0b904f4494e14e2fbb6adc85a10c941699f70483f001ca0f7351bfbed912c58697ae3d6dd031f6c2dbf14cbc74aedcc88a56f06d3172d5c08f42e3134c235ae3f85ed257dddf8348aa57e805eda7e3d5e4bb517480358d16cf5f6c91b11cf91a69617b93e4591cfe9e159f0a60dd0b26ad3ec44b66f1c13228955b4772a952fdfc8706544bf6f0aeafad42c1001f0278c52b93e9d40297d8ac21cde09f9c3e392c43fee6972054dae6a69d84d61cb38056484258b6ffd09f69170e9a8539caf3432322137bb75a2d77e4523550e3ebecf6a07a5b667230cd44" -O data.zip
!unzip data.zip

--2026-03-07 06:03:16--  https://storage.googleapis.com/kaggle-data-sets/306/666/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260307%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260307T054502Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=187c940c75e240ebfc9d161e8437a76f0b488efb40acb7d0fafb80ac1ed2690c8c95776259a94f0b904f4494e14e2fbb6adc85a10c941699f70483f001ca0f7351bfbed912c58697ae3d6dd031f6c2dbf14cbc74aedcc88a56f06d3172d5c08f42e3134c235ae3f85ed257dddf8348aa57e805eda7e3d5e4bb517480358d16cf5f6c91b11cf91a69617b93e4591cfe9e159f0a60dd0b26ad3ec44b66f1c13228955b4772a952fdfc8706544bf6f0aeafad42c1001f0278c52b93e9d40297d8ac21cde09f9c3e392c43fee6972054dae6a69d84d61cb38056484258b6ffd09f69170e9a8539caf3432322137bb75a2d77e4523550e3ebecf6a07a5b667230cd44
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.101.207, 142.250.141.207, 142.251.2.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.101.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1025318 (1001K) [application/zip]
Saving to: ‘data.zip’

data.zip            100%[===================>]   1001K  --.-KB/s    in 0.007s

2026-03-07 06:03:17 (138 MB/s) - ‘data.zip’ saved [1025318/1025318]

Archive:  data.zip
  inflating: UCI_Credit_Card.csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('UCI_Credit_Card.csv')

In [ ]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [ ]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   30000 non-null  float64
 14  BILL_AMT3                   30000 non-null  float64
 15  BILL_AMT4                   30000 non-null  float64
 16  BILL_AMT5                   30000 non-null  float64
 17  BILL_AMT6                   30000 non-null  float64
 18  PAY_AMT1                    30000 non-null  float64
 19  PAY_AMT2                    30000 non-null  float64
 20  PAY_AMT3                    30000 non-null  float64
 21  PAY_AMT4                    30000 non-null  float64
 22  PAY_AMT5                    30000 non-null  float64
 23  PAY_AMT6                    30000 non-null  float64
 24  default.payment.next.month  30000 non-null  int64
dtypes: float64(13), int64(12)
memory usage: 5.7 MB

In [ ]:
print("Unique values for SEX:", df['SEX'].unique())
print("Unique values for EDUCATION:", df['EDUCATION'].unique())
print("Unique values for MARRIAGE:", df['MARRIAGE'].unique())

Unique values for SEX: [2 1]
Unique values for EDUCATION: [2 1 3 5 4 6 0]
Unique values for MARRIAGE: [1 2 3 0]

In [ ]:
df['EDUCATION'] = df['EDUCATION'].replace({0: 4, 5: 4, 6: 4})
df['MARRIAGE'] = df['MARRIAGE'].replace({0: 3})

print("Unique values for EDUCATION after mapping:", df['EDUCATION'].unique())
print("Unique values for MARRIAGE after mapping:", df['MARRIAGE'].unique())

Unique values for EDUCATION after mapping: [2 1 3 4]
Unique values for MARRIAGE after mapping: [1 2 3]

In [ ]:
df = pd.get_dummies(df, columns=['SEX', 'EDUCATION', 'MARRIAGE'], drop_first=False)
df.head()

,ID,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,default.payment.next.month,SEX_1,SEX_2,EDUCATION_1,EDUCATION_2,EDUCATION_3,EDUCATION_4,MARRIAGE_1,MARRIAGE_2,MARRIAGE_3
0,1,20000.0,24,2,2,-1,-1,-2,-2,3913.0,...,1,False,True,False,True,False,False,True,False,False
1,2,120000.0,26,-1,2,0,0,0,2,2682.0,...,1,False,True,False,True,False,False,False,True,False
2,3,90000.0,34,0,0,0,0,0,0,29239.0,...,0,False,True,False,True,False,False,False,True,False
3,4,50000.0,37,0,0,0,0,0,0,46990.0,...,0,False,True,False,True,False,False,True,False,False
4,5,50000.0,57,-1,0,-1,0,0,0,8617.0,...,0,True,False,False,True,False,False,True,False,False

In [ ]:
pay_columns = ['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']
df['num_late_payments'] = (df[pay_columns] > 0).sum(axis=1)
df.head()

,ID,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,SEX_1,SEX_2,EDUCATION_1,EDUCATION_2,EDUCATION_3,EDUCATION_4,MARRIAGE_1,MARRIAGE_2,MARRIAGE_3,num_late_payments
0,1,20000.0,24,2,2,-1,-1,-2,-2,3913.0,...,False,True,False,True,False,False,True,False,False,2
1,2,120000.0,26,-1,2,0,0,0,2,2682.0,...,False,True,False,True,False,False,False,True,False,2
2,3,90000.0,34,0,0,0,0,0,0,29239.0,...,False,True,False,True,False,False,False,True,False,0
3,4,50000.0,37,0,0,0,0,0,0,46990.0,...,False,True,False,True,False,False,True,False,False,0
4,5,50000.0,57,-1,0,-1,0,0,0,8617.0,...,True,False,False,True,False,False,True,False,False,0

In [ ]:
X = df.drop(['ID', 'default.payment.next.month'], axis=1)
y = df['default.payment.next.month']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (24000, 30)
X_test shape: (6000, 30)
y_train shape: (24000,)
y_test shape: (6000,)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)
print("Decision Tree Classifier trained successfully.")

Decision Tree Classifier trained successfully.

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(random_state=42)
rf_classifier.fit(X_train, y_train)
print("Random Forest Classifier trained successfully.")

Random Forest Classifier trained successfully.

In [ ]:
import xgboost as xgb

xgb_classifier = xgb.XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb_classifier.fit(X_train, y_train)
print("XGBoost Classifier trained successfully.")

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [06:03:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBoost Classifier trained successfully.

In [ ]:
from sklearn.metrics import classification_report

# Make predictions for Decision Tree
y_pred_dt = dt_classifier.predict(X_test)

# Evaluate Decision Tree
print("--- Decision Tree Classifier ---")
print(classification_report(y_test, y_pred_dt))

--- Decision Tree Classifier ---
              precision    recall  f1-score   support

           0       0.83      0.81      0.82      4673
           1       0.38      0.41      0.39      1327

    accuracy                           0.72      6000
   macro avg       0.60      0.61      0.61      6000
weighted avg       0.73      0.72      0.72      6000

In [ ]:
y_pred_rf = rf_classifier.predict(X_test)

print("--- Random Forest Classifier ---")
print(classification_report(y_test, y_pred_rf))

--- Random Forest Classifier ---
              precision    recall  f1-score   support

           0       0.84      0.94      0.89      4673
           1       0.63      0.38      0.47      1327

    accuracy                           0.81      6000
   macro avg       0.74      0.66      0.68      6000
weighted avg       0.79      0.81      0.79      6000

In [ ]:
y_pred_xgb = xgb_classifier.predict(X_test)

print("--- XGBoost Classifier ---")
print(classification_report(y_test, y_pred_xgb))

--- XGBoost Classifier ---
              precision    recall  f1-score   support

           0       0.84      0.94      0.88      4673
           1       0.62      0.35      0.44      1327

    accuracy                           0.81      6000
   macro avg       0.73      0.64      0.66      6000
weighted avg       0.79      0.81      0.79      6000

## Hyperparameter Tuning - Random Forest

### Subtask:
Define a parameter grid for the Random Forest Classifier and perform hyperparameter tuning using GridSearchCV to find the optimal parameters.

**Reasoning**:
The subtask requires performing hyperparameter tuning for the Random Forest Classifier using `GridSearchCV`. This involves importing necessary libraries, defining a parameter grid, initializing and fitting `GridSearchCV`, and then printing the best parameters and score.

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for Random Forest
param_grid_rf = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

# Initialize GridSearchCV
grid_search_rf = GridSearchCV(
    estimator=rf_classifier,  # Using the previously trained rf_classifier
    param_grid=param_grid_rf,
    cv=5,                     # 5-fold cross-validation
    scoring='f1',             # F1-score as the evaluation metric
    n_jobs=-1                 # Use all available processors
)

# Fit GridSearchCV to the training data
grid_search_rf.fit(X_train, y_train)

# Print the best parameters and best F1-score
print("Best parameters for Random Forest:", grid_search_rf.best_params_)
print("Best F1-score for Random Forest:", grid_search_rf.best_score_)

Best parameters for Random Forest: {'max_depth': 20, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 200}
Best F1-score for Random Forest: 0.4777536207831866

**Reasoning**:
After running GridSearchCV, it's important to store the best performing model. This model will be used later to make predictions on the test set and evaluate its performance against the other models.

In [ ]:
best_rf_classifier = grid_search_rf.best_estimator_
print("Best Random Forest Classifier stored successfully.")

Best Random Forest Classifier stored successfully.

## Evaluate Tuned Random Forest

### Subtask:
Evaluate the performance of the Random Forest Classifier with the optimized hyperparameters on the test set.

**Reasoning**:
To evaluate the performance of the tuned Random Forest Classifier, I need to make predictions on the test set using the `best_rf_classifier` and then generate a classification report.

In [ ]:
y_pred_tuned_rf = best_rf_classifier.predict(X_test)

print("--- Tuned Random Forest Classifier ---")
print(classification_report(y_test, y_pred_tuned_rf))

--- Tuned Random Forest Classifier ---
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4673
           1       0.65      0.36      0.46      1327

    accuracy                           0.81      6000
   macro avg       0.74      0.65      0.67      6000
weighted avg       0.80      0.81      0.79      6000

## Hyperparameter Tuning - XGBoost

### Subtask:
Define a parameter grid for the XGBoost Classifier and perform hyperparameter tuning using GridSearchCV to find the optimal parameters.

**Reasoning**:
The subtask requires defining a parameter grid for the XGBoost Classifier, initializing and fitting GridSearchCV, and then printing the best parameters and score. Finally, the best estimator needs to be stored for future use.

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for XGBoost
param_grid_xgb = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.1, 0.01],
    'subsample': [0.8, 1.0]
}

# Initialize GridSearchCV
grid_search_xgb = GridSearchCV(
    estimator=xgb_classifier,  # Using the previously trained xgb_classifier
    param_grid=param_grid_xgb,
    cv=5,                      # 5-fold cross-validation
    scoring='f1',              # F1-score as the evaluation metric
    n_jobs=-1                  # Use all available processors
)

# Fit GridSearchCV to the training data
grid_search_xgb.fit(X_train, y_train)

# Print the best parameters and best F1-score
print("Best parameters for XGBoost:", grid_search_xgb.best_params_)
print("Best F1-score for XGBoost:", grid_search_xgb.best_score_)

# Store the best estimator
best_xgb_classifier = grid_search_xgb.best_estimator_
print("Best XGBoost Classifier stored successfully.")

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [06:12:48] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best parameters for XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'subsample': 0.8}
Best F1-score for XGBoost: 0.4776814097323565
Best XGBoost Classifier stored successfully.

**Reasoning**:
The subtask requires defining a parameter grid for the XGBoost Classifier, initializing and fitting GridSearchCV, and then printing the best parameters and score. Finally, the best estimator needs to be stored for future use.

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for XGBoost
param_grid_xgb = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.1, 0.01],
    'subsample': [0.8, 1.0]
}

# Initialize GridSearchCV
grid_search_xgb = GridSearchCV(
    estimator=xgb_classifier,  # Using the previously trained xgb_classifier
    param_grid=param_grid_xgb,
    cv=5,                      # 5-fold cross-validation
    scoring='f1',              # F1-score as the evaluation metric
    n_jobs=-1                  # Use all available processors
)

# Fit GridSearchCV to the training data
grid_search_xgb.fit(X_train, y_train)

# Print the best parameters and best F1-score
print("Best parameters for XGBoost:", grid_search_xgb.best_params_)
print("Best F1-score for XGBoost:", grid_search_xgb.best_score_)

# Store the best estimator
best_xgb_classifier = grid_search_xgb.best_estimator_
print("Best XGBoost Classifier stored successfully.")

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [06:13:27] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best parameters for XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'subsample': 0.8}
Best F1-score for XGBoost: 0.4776814097323565
Best XGBoost Classifier stored successfully.

**Reasoning**:
After hyperparameter tuning, the next logical step is to evaluate the performance of the optimized XGBoost Classifier on the test set using the best estimator obtained from GridSearchCV.

In [ ]:
y_pred_tuned_xgb = best_xgb_classifier.predict(X_test)

print("--- Tuned XGBoost Classifier ---")
print(classification_report(y_test, y_pred_tuned_xgb))

--- Tuned XGBoost Classifier ---
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4673
           1       0.67      0.36      0.47      1327

    accuracy                           0.82      6000
   macro avg       0.75      0.65      0.68      6000
weighted avg       0.80      0.82      0.80      6000

**Reasoning**:
The `NameError` indicates that `best_xgb_classifier` was not defined when the cell was executed. This variable is expected to be initialized by the preceding hyperparameter tuning step for XGBoost. Assuming the tuning step has been or will be executed successfully to define `best_xgb_classifier`, the evaluation code itself is correct and just needs to be re-run in the correct environment.

In [ ]:
y_pred_tuned_xgb = best_xgb_classifier.predict(X_test)

print("--- Tuned XGBoost Classifier ---")
print(classification_report(y_test, y_pred_tuned_xgb))

--- Tuned XGBoost Classifier ---
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4673
           1       0.67      0.36      0.47      1327

    accuracy                           0.82      6000
   macro avg       0.75      0.65      0.68      6000
weighted avg       0.80      0.82      0.80      6000

**Reasoning**:
The `NameError` occurred because `best_xgb_classifier` was not defined. This variable is created during the hyperparameter tuning step for XGBoost. The notebook history shows that the cell responsible for defining `best_xgb_classifier` (cell_id: `ac437e72` or `dd331642`) has not been executed yet. To resolve this, I need to execute the XGBoost hyperparameter tuning step first.

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for XGBoost
param_grid_xgb = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.1, 0.01],
    'subsample': [0.8, 1.0]
}

# Initialize GridSearchCV
grid_search_xgb = GridSearchCV(
    estimator=xgb_classifier,  # Using the previously trained xgb_classifier
    param_grid=param_grid_xgb,
    cv=5,                      # 5-fold cross-validation
    scoring='f1',              # F1-score as the evaluation metric
    n_jobs=-1                  # Use all available processors
)

# Fit GridSearchCV to the training data
grid_search_xgb.fit(X_train, y_train)

# Print the best parameters and best F1-score
print("Best parameters for XGBoost:", grid_search_xgb.best_params_)
print("Best F1-score for XGBoost:", grid_search_xgb.best_score_)

# Store the best estimator
best_xgb_classifier = grid_search_xgb.best_estimator_
print("Best XGBoost Classifier stored successfully.")

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [06:14:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best parameters for XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'subsample': 0.8}
Best F1-score for XGBoost: 0.4776814097323565
Best XGBoost Classifier stored successfully.

**Reasoning**:
The previous code block failed with a `NameError` because `xgb_classifier` was not defined. This variable should have been defined earlier when the initial XGBoost model was trained. I need to re-initialize the `xgb_classifier` before proceeding with `GridSearchCV`.

In [ ]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

# Re-initialize xgb_classifier as it was not in the kernel state
xgb_classifier = xgb.XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')

# Define the parameter grid for XGBoost
param_grid_xgb = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.1, 0.01],
    'subsample': [0.8, 1.0]
}

# Initialize GridSearchCV
grid_search_xgb = GridSearchCV(
    estimator=xgb_classifier,  # Using the previously trained xgb_classifier
    param_grid=param_grid_xgb,
    cv=5,                      # 5-fold cross-validation
    scoring='f1',              # F1-score as the evaluation metric
    n_jobs=-1                  # Use all available processors
)

# Fit GridSearchCV to the training data
grid_search_xgb.fit(X_train, y_train)

# Print the best parameters and best F1-score
print("Best parameters for XGBoost:", grid_search_xgb.best_params_)
print("Best F1-score for XGBoost:", grid_search_xgb.best_score_)

# Store the best estimator
best_xgb_classifier = grid_search_xgb.best_estimator_
print("Best XGBoost Classifier stored successfully.")

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [06:14:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best parameters for XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'subsample': 0.8}
Best F1-score for XGBoost: 0.4776814097323565
Best XGBoost Classifier stored successfully.

**Reasoning**:
The current `NameError` indicates that `X_train` and `y_train` are not defined in the current kernel state. These variables were created by the `train_test_split` function earlier in the notebook. I need to re-execute the `train_test_split` cell to recreate `X_train`, `X_test`, `y_train`, and `y_test` before proceeding with `GridSearchCV` for the XGBoost model. Additionally, I need to re-initialize the `xgb_classifier` and `GridSearchCV` for Random Forest and XGBoost as the kernel state seems to have been completely lost, affecting other variables like `rf_classifier` and `xgb_classifier` that were previously defined.

In [ ]:
X = df.drop(['ID', 'default.payment.next.month'], axis=1)
y = df['default.payment.next.month']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (24000, 30)
X_test shape: (6000, 30)
y_train shape: (24000,)
y_test shape: (6000,)

**Reasoning**:
The previous error indicated that the DataFrame `df` was not defined. This means the kernel state was lost or the preceding data loading and preprocessing steps were not executed. To resolve this, I need to re-execute all the necessary steps from loading the data to preprocessing it and then splitting it into training and testing sets, ensuring `df`, `X`, `y`, `X_train`, `X_test`, `y_train`, and `y_test` are correctly defined.

In [ ]:
import pandas as pd

df = pd.read_csv('UCI_Credit_Card.csv')

# Data preprocessing steps from earlier cells
df['EDUCATION'] = df['EDUCATION'].replace({0: 4, 5: 4, 6: 4})
df['MARRIAGE'] = df['MARRIAGE'].replace({0: 3})
df = pd.get_dummies(df, columns=['SEX', 'EDUCATION', 'MARRIAGE'], drop_first=False)
pay_columns = ['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']
df['num_late_payments'] = (df[pay_columns] > 0).sum(axis=1)

# Split data into features and target, then into training and testing sets
X = df.drop(['ID', 'default.payment.next.month'], axis=1)
y = df['default.payment.next.month']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("DataFrame and split data re-initialized successfully.")
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

DataFrame and split data re-initialized successfully.
X_train shape: (24000, 30)
X_test shape: (6000, 30)
y_train shape: (24000,)
y_test shape: (6000,)

**Reasoning**:
Now that `df`, `X_train`, `X_test`, `y_train`, and `y_test` are correctly defined, I need to re-initialize the `xgb_classifier` and then perform the hyperparameter tuning for XGBoost using `GridSearchCV`. This ensures all required variables are in the kernel state before execution.

In [ ]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

# Re-initialize xgb_classifier
xgb_classifier = xgb.XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')

# Define the parameter grid for XGBoost
param_grid_xgb = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.1, 0.01],
    'subsample': [0.8, 1.0]
}

# Initialize GridSearchCV
grid_search_xgb = GridSearchCV(
    estimator=xgb_classifier,  # Using the re-initialized xgb_classifier
    param_grid=param_grid_xgb,
    cv=5,                      # 5-fold cross-validation
    scoring='f1',              # F1-score as the evaluation metric
    n_jobs=-1                  # Use all available processors
)

# Fit GridSearchCV to the training data
grid_search_xgb.fit(X_train, y_train)

# Print the best parameters and best F1-score
print("Best parameters for XGBoost:", grid_search_xgb.best_params_)
print("Best F1-score for XGBoost:", grid_search_xgb.best_score_)

# Store the best estimator
best_xgb_classifier = grid_search_xgb.best_estimator_
print("Best XGBoost Classifier stored successfully.")

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [06:15:26] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best parameters for XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'subsample': 0.8}
Best F1-score for XGBoost: 0.4776814097323565
Best XGBoost Classifier stored successfully.

**Reasoning**:
The previous steps successfully re-initialized the DataFrame and split it into training and testing sets. Now, I need to proceed with the hyperparameter tuning for XGBoost, which involves re-initializing the XGBoost classifier, defining the parameter grid, performing GridSearchCV, and storing the best estimator. This directly addresses the current subtask instructions.

In [ ]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

# Re-initialize xgb_classifier
xgb_classifier = xgb.XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')

# Define the parameter grid for XGBoost
param_grid_xgb = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.1, 0.01],
    'subsample': [0.8, 1.0]
}

# Initialize GridSearchCV
grid_search_xgb = GridSearchCV(
    estimator=xgb_classifier,  # Using the re-initialized xgb_classifier
    param_grid=param_grid_xgb,
    cv=5,                      # 5-fold cross-validation
    scoring='f1',              # F1-score as the evaluation metric
    n_jobs=-1                  # Use all available processors
)

# Fit GridSearchCV to the training data
grid_search_xgb.fit(X_train, y_train)

# Print the best parameters and best F1-score
print("Best parameters for XGBoost:", grid_search_xgb.best_params_)
print("Best F1-score for XGBoost:", grid_search_xgb.best_score_)

# Store the best estimator
best_xgb_classifier = grid_search_xgb.best_estimator_
print("Best XGBoost Classifier stored successfully.")

## Evaluate Tuned XGBoost

### Subtask:
Evaluate the performance of the XGBoost Classifier with the optimized hyperparameters on the test set.

## Summary:

### Q&A
1.  **Were the hyperparameters tuned for Random Forest and XGBoost classifiers?**
    Yes, hyperparameters for both Random Forest and XGBoost classifiers were tuned using `GridSearchCV`.
2.  **Were the optimized models evaluated on the test set?**
    Yes, both the tuned Random Forest and XGBoost models were evaluated on the test set, and their performance metrics were generated.

### Data Analysis Key Findings
*   **Random Forest Hyperparameter Tuning:** The Random Forest classifier was successfully tuned using `GridSearchCV` with a defined parameter grid (`n_estimators`, `max_depth`, `min_samples_split`, `min_samples_leaf`). Optimal parameters and the best F1-score (specific values not provided) were identified using 5-fold cross-validation. The best performing model was stored for evaluation.
*   **Random Forest Evaluation:** The optimized Random Forest classifier's performance was evaluated on the test set, generating a classification report including metrics such as precision, recall, and F1-score.
*   **XGBoost Hyperparameter Tuning:** After resolving initial environment issues related to undefined variables, the XGBoost classifier was successfully tuned using `GridSearchCV`. A parameter grid including `n_estimators`, `max_depth`, `learning_rate`, and `subsample` was explored, and optimal parameters and the best F1-score (specific values not provided) were identified through 5-fold cross-validation. The best performing model was stored.
*   **XGBoost Evaluation:** The optimized XGBoost classifier's performance was evaluated on the test set, providing a classification report with relevant metrics.

### Insights or Next Steps
*   Compare the specific performance metrics (F1-score, precision, recall) from the classification reports of both tuned models on the test set to determine which classifier performs best for this specific problem.
*   Consider further model optimization, such as exploring a wider range of hyperparameters, using different cross-validation strategies, or employing ensemble methods if neither tuned model achieves satisfactory performance.